### ISSUE TITLE
reshape-image

### ISSUE THREAD

**Issue by Shyam-Chen** [reshape/reshape#39]
https://github.com/jonathantneal/posthtml-inline-assets

https://github.com/postcss/postcss-url

**Comment by jescalan** [comment]
Hi Shaym,

Again, this issue does not have enough detail to stay open right now. We have a great [contributing guide](https://github.com/reshape/reshape/blob/master/contributing.md#filing-issues) that might help when filing new issues! If you can add some more detail here and make it more clear what you are asking about, we can re-open and address it then.
