### ISSUE TITLE
__runtime.escape(...) in html

### ISSUE THREAD

**Issue by waynehoover** [reshape/reshape#46]
Hi,

I'm using Spike with some data loaded via Records, and when I try and render this markdown data with 

``div(md) {{ item.fields.content }}`` in my template I get ``__runtime.escape(item.fields.content)`` straight in my HTML. 

Let me know if you need more context. Pretty standard Spike 1.3 config

**Comment by tkraak** [comment]
@waynehoover ... [this faq](https://spike.readme.io/docs/faqs#section-markdown-processing-locals) explains what's happening. Thanks for using spike!

**Comment by jescalan** [comment]
Yep, also [this issue](https://github.com/static-dev/spike/issues/67). I'm going to close this since it's taken care of but by all means let us know if there's any other issues you're running into!
