### ISSUE TITLE
Issue with HTML entities getting decoded

### ISSUE THREAD

**Issue by gionkunz** [reshape/reshape#61]
Hi
I'm using spike for a project the first time. I've noticed that if I'm putting HTML entities into attribute values in HTML templates, they get decoded and end up like that in the HTML output which is not desirable.

This example:
```html
<div data-options="{&quot;name&quot;: &quot;Test&quot;}"></div>
```

results in:
```html
<div data-options="{"name": "Test"}"></div>
```

**Comment by jescalan** [comment]
Hey @gionkunz! Thanks for reporting this - I did a bit of testing and traced it back to an issue with [parse5](https://github.com/inikulin/parse5), the html parser that reshape utilizes. It looks like the html entities are resolved as part of the parsing of the attributes. I'm not sure why this is the case, and have [opened an issue in parse5 to ask about it](https://github.com/inikulin/parse5/issues/241), which we can use to track progress.

**Comment by gionkunz** [comment]
Hey. :-) Cool, thanks!

**Comment by jescalan** [comment]
Ok, so I know this is SUPER late but I have this resolved now.

https://github.com/reshape/code-gen/pull/32

Will have this merged and shipped out tomorrow morning. Confusing, but ultimately a fairly small fix!

**Comment by gionkunz** [comment]
Awesome! No worries, thats the thibg with opensource, it takes time... :-)
