### ISSUE TITLE
Integration with VSCode prettier for Vue

### ISSUE THREAD

**Issue by popo63301** [reshape/reshape#69]
Hi! 

Any plan to integrate this with Vetur to format Vue's template for VSCode? I'd love to use Prettier correctly with Vue in VScode, but it seems to not work yet.

**Comment by jescalan** [comment]
I honestly have no idea what you're talking about, I'm sorry. I don't know what vetur is, and I do not use vue, or vscode. So I think I can probably say fairly confidently that it's not something that I personally was planning on doing.

**Comment by popo63301** [comment]
Hi! Sorry, I was juggling between different GitHub repos.
I saw you responded to @octref, main maintenaire of https://github.com/vuejs/vetur in this thread: https://github.com/prettier/prettier/issues/1882 

<img width="898" alt="screen shot 2018-06-11 at 01 17 42" src="https://user-images.githubusercontent.com/29427340/41207382-74a4b588-6d15-11e8-873b-d0da7fecbfb4.png">

I thought this project was related to Vetur (the  VSCode extension that allows you to have some color in your Vue code) and its problem to format HTML. Sorry for opening this issue ! 😄

**Comment by jescalan** [comment]
Yep, that was in regard to prettier - there hasn't been any more movement there either though.
