### ISSUE TITLE
website broken links

### ISSUE THREAD

**Issue by tomByrer** [reshape/reshape#73]
Your website currently has links to old sub-pages:
eg entry: https://reshape.js.org/
but "Plugins" links to: http://plugins.reshape.ml/

Also, the footer should be updated IMHO.

Thanks for your repo; I'll have to play with it in a few days!

**Comment by jescalan** [comment]
Hi there! You're right, I had some hosting provider issues which ended up taking down the plugins site, and I don't have the bandwidth to get it back up at the moment. And why is it that you think the footer should be updated? It's still true 😁

**Comment by tomByrer** [comment]
Need to have a hosting provider to list plugins?  Maybe just use GitHub's WiKi, edit README, or just use [npm's search](https://www.npmjs.com/search?q=keywords:reshape-plugin)?

Footer: company merged

**Comment by jescalan** [comment]
I've got a nice little plugin directory project I was using for it here: https://github.com/carrot/plugin-directory

**Comment by jescalan** [comment]
Sorry for the very long delay but this is working now
